### ISSUE TITLE
Can't connect to any server.

### ISSUE THREAD

**Issue by oa3856** [haxball/haxball-issues#117]
This is all that happens when i try to connect. https://imgur.com/QyNSqce
I already disabled all adblockers and tried it on torch (which is pretty much chrome), and firefox, yet it doesn't work.
No one can join when I host either, idk what to do. Flash version is the only one that works.
![aa4e241eea80bbe6d052f0a6609db585](https://user-images.githubusercontent.com/23567062/32363419-856e27be-c02c-11e7-9921-d39ea65d26ff.gif)

**Comment by basro** [comment]
Hello, please follow this instructions and report back:
1) Right click -> Inspect
2) Try to join a room
3) In the inspector go to the console tab, copy everything in the console and paste it here

**Comment by oa3856** [comment]
A Parser-blocking, cross-origin script, http://server.cpmstar.com/view.aspx?poolid=26640&script=1&rnd=645595, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity. See https://www.chromestatus.com/feature/5718547946799104 for more details.
(anonymous) @ index.html:37
DragAndDropController.js:89 extension connect
DragAndDropController.js:185 onExtensionMsgReceived:ddBgIsReady
DragAndDropController.js:185 onExtensionMsgReceived:getSettings
DragAndDropController.js:185 onExtensionMsgReceived:windowIsActivated
DragAndDropController.js:39 DragAndDropController::getprofilePrefs() settings are null
content.js:26 Test error!
Error  :    TypeError
desc   :    Cannot read property 'default_search_provider' of null
stack  :    TypeError: Cannot read property 'default_search_provider' of null
    at WebSearchActionProvider.getParams (chrome-extension://cipmepknanmbbaneimacddfemfbfgpgo/js/classes/ActionProvider.js:258:20)
    at DropArea.getActionProviderParams (chrome-extension://cipmepknanmbbaneimacddfemfbfgpgo/js/classes/DropAreas.js:73:37)
    at DropArea.create (chrome-extension://cipmepknanmbbaneimacddfemfbfgpgo/js/classes/DropAreas.js:14:50)
    at DropAreas.create (chrome-extension://cipmepknanmbbaneimacddfemfbfgpgo/js/classes/DropAreas.js:206:38)
    at WinDragSurface.createSearchDropAreas (chrome-extension://cipmepknanmbbaneimacddfemfbfgpgo/js/classes/DragSurface.js:15:26)
    at DragAndDropController.onExtensionMsgReceived (chrome-extension://cipmepknanmbbaneimacddfemfbfgpgo/js/classes/DragAndDropController.js:161:29)
    at chrome-extension://cipmepknanmbbaneimacddfemfbfgpgo/js/content.js:4:22
    at EventImpl.dispatchToListener (extensions::event_bindings:388:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:149:26)
    at EventImpl.dispatch_ (extensions::event_bindings:372:35)
DragAndDropController.js:185 onExtensionMsgReceived:getShareSources
DragAndDropController.js:185 onExtensionMsgReceived:windowIsActivated
DragAndDropController.js:185 onExtensionMsgReceived:ddBgIsReady
DragAndDropController.js:185 onExtensionMsgReceived:getSettings
DragAndDropController.js:185 onExtensionMsgReceived:getSearchSources
DragAndDropController.js:185 onExtensionMsgReceived:getShareSources
DragAndDropController.js:185 onExtensionMsgReceived:ddBgIsReady
DragAndDropController.js:185 onExtensionMsgReceived:getSettings
DragAndDropController.js:185 onExtensionMsgReceived:getSearchSources
DragAndDropController.js:185 onExtensionMsgReceived:getShareSources
VM389:334 Uncaught TypeError: Failed to construct 'RTCPeerConnection': Malformed RTCIceServer
    at WrappedRTCPeerConnection (<anonymous>:334:26)
    at WrappedRTCPeerConnection (<anonymous>:331:26)
    at za [as g] (game-min.js:35)
    at xb [as g] (game-min.js:36)
    at d (game-min.js:32)
    at ib [as g] (game-min.js:32)
    at Function.l.mf (game-min.js:108)
    at a.Ri (game-min.js:104)
    at Function.z.l (game-min.js:85)
    at HTMLTableRowElement.<anonymous> (game-min.js:187)
2DragAndDropController.js:185 onExtensionMsgReceived:ddBgIsReady
2DragAndDropController.js:185 onExtensionMsgReceived:getSettings
DragAndDropController.js:185 onExtensionMsgReceived:ddBgIsReady
DragAndDropController.js:185 onExtensionMsgReceived:getSearchSources
DragAndDropController.js:185 onExtensionMsgReceived:getShareSources
DragAndDropController.js:185 onExtensionMsgReceived:getSearchSources
DragAndDropController.js:185 onExtensionMsgReceived:getShareSources
DragAndDropController.js:185 onExtensionMsgReceived:getSettings
DragAndDropController.js:185 onExtensionMsgReceived:getSearchSources
DragAndDropController.js:185 onExtensionMsgReceived:getShareSources

**Comment by oa3856** [comment]
A Parser-blocking, cross-origin script, http://server.cpmstar.com/view.aspx?poolid=26640&script=1&rnd=949809, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity. See https://www.chromestatus.com/feature/5718547946799104 for more details.
(anonymous) @ index.html:37
DragAndDropController.js:89 extension connect
DragAndDropController.js:185 onExtensionMsgReceived:ddBgIsReady
DragAndDropController.js:185 onExtensionMsgReceived:windowIsActivated
DragAndDropController.js:185 onExtensionMsgReceived:getSettings
DragAndDropController.js:39 DragAndDropController::getprofilePrefs() settings are null
content.js:26 Test error!
Error  :    TypeError
desc   :    Cannot read property 'default_search_provider' of null
stack  :    TypeError: Cannot read property 'default_search_provider' of null
    at WebSearchActionProvider.getParams (chrome-extension://cipmepknanmbbaneimacddfemfbfgpgo/js/classes/ActionProvider.js:258:20)
    at DropArea.getActionProviderParams (chrome-extension://cipmepknanmbbaneimacddfemfbfgpgo/js/classes/DropAreas.js:73:37)
    at DropArea.create (chrome-extension://cipmepknanmbbaneimacddfemfbfgpgo/js/classes/DropAreas.js:14:50)
    at DropAreas.create (chrome-extension://cipmepknanmbbaneimacddfemfbfgpgo/js/classes/DropAreas.js:206:38)
    at WinDragSurface.createSearchDropAreas (chrome-extension://cipmepknanmbbaneimacddfemfbfgpgo/js/classes/DragSurface.js:15:26)
    at DragAndDropController.onExtensionMsgReceived (chrome-extension://cipmepknanmbbaneimacddfemfbfgpgo/js/classes/DragAndDropController.js:161:29)
    at chrome-extension://cipmepknanmbbaneimacddfemfbfgpgo/js/content.js:4:22
    at EventImpl.dispatchToListener (extensions::event_bindings:388:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:149:26)
    at EventImpl.dispatch_ (extensions::event_bindings:372:35)
DragAndDropController.js:185 onExtensionMsgReceived:getShareSources
DragAndDropController.js:185 onExtensionMsgReceived:windowIsActivated
DragAndDropController.js:185 onExtensionMsgReceived:ddBgIsReady
DragAndDropController.js:185 onExtensionMsgReceived:getSettings
DragAndDropController.js:185 onExtensionMsgReceived:getSearchSources
DragAndDropController.js:185 onExtensionMsgReceived:getShareSources
DragAndDropController.js:185 onExtensionMsgReceived:ddBgIsReady
DragAndDropController.js:185 onExtensionMsgReceived:getSettings
DragAndDropController.js:185 onExtensionMsgReceived:getSearchSources
DragAndDropController.js:185 onExtensionMsgReceived:getShareSources
VM799:334 Uncaught TypeError: Failed to construct 'RTCPeerConnection': Malformed RTCIceServer
    at WrappedRTCPeerConnection (<anonymous>:334:26)
    at WrappedRTCPeerConnection (<anonymous>:331:26)
    at za [as g] (game-min.js:35)
    at xb [as g] (game-min.js:36)
    at d (game-min.js:32)
    at ib [as g] (game-min.js:32)
    at Function.l.mf (game-min.js:108)
    at a.Ri (game-min.js:104)
    at Function.z.l (game-min.js:85)
    at HTMLTableRowElement.<anonymous> (game-min.js:187)
WrappedRTCPeerConnection @ VM799:334
WrappedRTCPeerConnection @ VM800:331
za @ game-min.js:35
xb @ game-min.js:36
d @ game-min.js:32
ib @ game-min.js:32
l.mf @ game-min.js:108
a.Ri @ game-min.js:104
z.l @ game-min.js:85
(anonymous) @ game-min.js:187

**Comment by basro** [comment]
What version of chrome are you using?
Could you do the same with firefox as well?

**Comment by basro** [comment]
I believe you have some browser extension that is breaking HaxBall, but it's strange if it also happens in firefox unless you have installed the same extension in firefox as well.

Try disabling all browser extensions and trying again.

**Comment by basro** [comment]
I'd also like to know what your OS is.

**Comment by oa3856** [comment]
OS: Windows 8.1
Browser Version:
<img width="960" alt="torchver" src="https://user-images.githubusercontent.com/23567062/32396586-0cbad386-c0a3-11e7-98d1-f406b0bd21f1.PNG">

The only extension that I have on both Mozilla and Torch is AdblockPlus, but I already disabled it on both browsers for html5.haxball.com

**Comment by oa3856** [comment]
WOW I JUST UPDATED FIREFOX AND IT WORKS. THANKS. DISREGARD ABOVE.

**Comment by basro** [comment]
Good to hear!
I guess I'll try to handle that error you were getting so that haxball will at least give a warning instead of showing nothing.
