### ISSUE TITLE
How to host on chrome headless?

### ISSUE THREAD

**Issue by Wolf72** [haxball/haxball-issues#681]
Ok my host expired (one where I had CentOs with Gnome installed) so now I have host with only ssh console. How tf do I make it run 4 room all with different codes where 3 rooms are called from window.open from first room T_T. @basro help :d

**Comment by Wolf72** [comment]
`const puppeteer = require('puppeteer');
const rooms = require('./room.js');

puppeteer.launch().then(async browser => {
  const page = await browser.newPage();
  await page.goto('https://haxball.com/headless');
  await page.evaluate(rooms.loadRoom);
});
`
In room.js I stored room code wrapped inside function:
`//Room parameters
exports.loadRoom= function() {
  var room = HBInit({ roomName: "My room", public:true,maxPlayers: 16 });
  room.setDefaultStadium("Big");
  room.setScoreLimit(5);
  room.setTimeLimit(0);

  // If there are no admins left in the room give admin to one of the remaining players.
  function updateAdmins() {
    // Get all players except the host (id = 0 is always the host)
    var players = room.getPlayerList().filter((player) => player.id != 0 );
    if ( players.length == 0 ) return; // No players left, do nothing.
    if ( players.find((player) => player.admin) != null ) return; // There's an admin left so do nothing.
    room.setPlayerAdmin(players[0].id, true); // Give admin to the first non admin player in the list
  }

  room.onPlayerJoin = function(player) {
    updateAdmins();
  }

  room.onPlayerLeave = function(player) {
    updateAdmins();
  }
}
`

**Comment by olegmisar** [comment]
Because `HBInit` is not defined when you try to call it. Use this to init:
```js
window.onHBLoaded = () => {
  const room = window.HBInit({})
}
// To make sure room is initialized
if (typeof window.HBInit === 'function') window.onHBLoaded()
```

**Comment by Wolf72** [comment]
@olegmisar  
I have no idea where to put that and what does it do xD
Should I put my whole code inside onHBLoaded callback then?
And what is purpose of this callback?

**Comment by Wolf72** [comment]
Ok now my when I close node app my indexeddb database gets deleted why? :S

**Comment by droofdd** [comment]
@Wolf72 @olegmisar  : hi !

This is how i managed to host my room / bot on Scaleway VPS - Ubuntu 18.04 - Amsterdam :
1. Install chrome-headless (not chromium) - plenty tutorials on web
2. install nodejs + npm
3. create a folder for room / bot .js files
4. install npm puppeteer in the folder
5. create 2 .js files in folder
My examples have:
- haxbot.js (for run with node.js, initialise chrome headless etc)
- bot.js (the room itself with configurations, commands etc)

**haxbot.js**
```
const puppeteer = require('puppeteer');
async function bot () {
    const browser = await puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox']});
    const page = await browser.newPage();
    await page.goto('https://www.haxball.com/headless', {waitUntil: 'networkidle2'});
    await page.addScriptTag({path: 'bot.js'});
}
bot();
console.log('Bot loaded');
```
**bot.js**
```
var room = HBInit({
	roomName: "Drtoothy VPS",
	maxPlayers: 16,
    token: "go get token",
    public: true,
    playerName: "Bot",
    geo: {"code": "RO", "lat" : 44.4, "lon" : 26.1}
});
			
room.setDefaultStadium("Big");
room.setScoreLimit(3);
room.setTimeLimit(3);
room.setTeamsLock(true);
```
6. Test if all works fine with "node.js haxbot.js"
You will also see console output "Bot loaded"
Go test room on website
At this point, the node.js will keep running, but you cannot alt-tab the process because puppeteer runs as single thread. (info on the internet) 
If you press Ctrl+C it will close the process and stop the room.

7. Workaround for process closing
Install npm forever
Always start forever with --uid syntax because there will be problems on stopping (check the web)
```
forever start --uid "hax" haxbot.js
forever stop hax
```

I guess your codes are a bit better optimised and fluent.
@Wolf72 Maybe my step 7 will help you, but what is this "indexeddb database" you talking about ?

**Comment by luangs7** [comment]
> @Wolf72 @olegmisar : hi !
> 
> This is how i managed to host my room / bot on Scaleway VPS - Ubuntu 18.04 - Amsterdam :
> 
> 1. Install chrome-headless (not chromium) - plenty tutorials on web
> 2. install nodejs + npm
> 3. create a folder for room / bot .js files
> 4. install npm puppeteer in the folder
> 5. create 2 .js files in folder
>    My examples have:
> 
> * haxbot.js (for run with node.js, initialise chrome headless etc)
> * bot.js (the room itself with configurations, commands etc)
> 
> **haxbot.js**
> 
> ```
> const puppeteer = require('puppeteer');
> async function bot () {
>     const browser = await puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox']});
>     const page = await browser.newPage();
>     await page.goto('https://www.haxball.com/headless', {waitUntil: 'networkidle2'});
>     await page.addScriptTag({path: 'bot.js'});
> }
> bot();
> console.log('Bot loaded');
> ```
> 
> **bot.js**
> 
> ```
> var room = HBInit({
> 	roomName: "Drtoothy VPS",
> 	maxPlayers: 16,
>     token: "go get token",
>     public: true,
>     playerName: "Bot",
>     geo: {"code": "RO", "lat" : 44.4, "lon" : 26.1}
> });
> 			
> room.setDefaultStadium("Big");
> room.setScoreLimit(3);
> room.setTimeLimit(3);
> room.setTeamsLock(true);
> ```
> 
> 1. Test if all works fine with "node.js haxbot.js"
>    You will also see console output "Bot loaded"
>    Go test room on website
>    At this point, the node.js will keep running, but you cannot alt-tab the process because puppeteer runs as single thread. (info on the internet)
>    If you press Ctrl+C it will close the process and stop the room.
> 2. Workaround for process closing
>    Install npm forever
>    Always start forever with --uid syntax because there will be problems on stopping (check the web)
> 
> ```
> forever start --uid "hax" haxbot.js
> forever stop hax
> ```
> 
> I guess your codes are a bit better optimised and fluent.
> What other ways are you using to run the scripts ?
> @Wolf72 Maybe my step 7 will help you, but what is this "indexeddb database" you talking about ?

Doing the same as you and getting 
`SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/user/node_modules/puppeteer/lib/cjs/puppeteer/common/Target.js:19:19)`

**Comment by luangs7** [comment]
I think the problem to use puppeteer is when need to pass captcha.
