### ISSUE TITLE
Headless-Browser problem

### ISSUE THREAD

**Issue by kaclam** [haxball/haxball-issues#837]
Hello, I wrote here last time about my problem. I host my room with headless chromium, puppeteer and forever. Unfortunately I have the same problem on each virtual machine.

On machine with more RAM, after few hours is ...trying reverse connection and then if you want to connect, is failed, then, closed.

On machine with less RAM, after few hours room is closed. 

In both scenario, when room is closed, this info is save in logs:

> (node:29629) UnhandledPromiseRejectionWarning: Error: Page crashed!
    at Page._onTargetCrashed (haxball/node_modules/puppeteer/lib/Page.js:215:24)
    at CDPSession.Page.client.on.event (haxball/node_modules/puppeteer/lib/Page.js:123:56)
    at emitOne (events.js:116:13)
    at CDPSession.emit (events.js:211:7)
    at CDPSession._onMessage (haxball/node_modules/puppeteer/lib/Connection.js:200:12)
    at Connection._onMessage (haxball/node_modules/puppeteer/lib/Connection.js:112:17)
    at WebSocketTransport._ws.addEventListener.event (haxball/node_modules/puppeteer/lib/WebSocketTransport.js:44:24)
    at WebSocket.onMessage (haxball/node_modules/ws/lib/event-target.js:120:16)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
(node:29629) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:29629) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.``

This problem is only with more demanding bot code. With empty bot code, room works good. But I think that the problem is not with code, cause I hosted a lot of rooms in last ~five months. Maybe its a problem with puppeteer installation or chromium? It looks like out of memory in headless browser.

**Comment by kingjasko** [comment]
I'm using google cloud with 1.7GB RAM, I believe and 2 I'm running 2 rooms simultaneously without any problems.

**Comment by kaclam** [comment]
Do you host on headless browser or with graphical environment? I dont have idea what happend. Which distro linux you use?

**Comment by kingjasko** [comment]
headless, ubuntu 16.04

**Comment by kaclam** [comment]
Ok, I do. I was using 18.04 but I think that its not the problem. Could you tell me about your configuration? What did you after chose the system? It will be helpful for me.

**Comment by dapucita** [comment]
> Ok, I do. I was using 18.04 but I think that its not the problem. Could you tell me about your configuration? What did you after chose the system? It will be helpful for me.

Would you like to review my code? I made my own bot using Puppeteer and Electron. I'm beginner and I'd met many problems on Puppeteer but I've solved almost of them. 
I've tested it on Windows 64bit, and old console version on Ubuntu 14.04LTS.

[haxbotron link](https://github.com/dapucita/haxbotron)
