### ISSUE TITLE
TypeError: a.substr is not a function

### ISSUE THREAD

**Issue by ToderitaGeorgeCristian** [haxball/haxball-issues#978]
@basro 
Hi !

Can you please tell why do I get this error ?
I am not using substr in my script so it must be from haxball scripts.

Guess it tries to read something and it is not there.
Some help on debugging would be great :)

**Comment by ToderitaGeorgeCristian** [comment]
More info from puppetter with pm2 on nodejs:

2020-01-09T21:34:08: pageerror:  [Error: TypeError: a.substr is not a function
2020-01-09T21:34:08:     at Function.H.substr (https://www.haxball.com/4WqKEIlM/__cache_static__/g/headless-min.js:12:173)
2020-01-09T21:34:08:     at Function.I.pb (https://www.haxball.com/4WqKEIlM/__cache_static__/g/headless-min.js:13:265)
2020-01-09T21:34:08:     at J.P (https://www.haxball.com/4WqKEIlM/__cache_static__/g/headless-min.js:112:457)
2020-01-09T21:34:08:     at Function.g.ie (https://www.haxball.com/4WqKEIlM/__cache_static__/g/headless-min.js:41:274)
2020-01-09T21:34:08:     at Ga.$e (https://www.haxball.com/4WqKEIlM/__cache_static__/g/headless-min.js:47:213)
2020-01-09T21:34:08:     at Ga.Bd (https://www.haxball.com/4WqKEIlM/__cache_static__/g/headless-min.js:47:134)
2020-01-09T21:34:08:     at Ga.cc (https://www.haxball.com/4WqKEIlM/__cache_static__/g/headless-min.js:45:286)
2020-01-09T21:34:08:     at https://www.haxball.com/4WqKEIlM/__cache_static__/g/headless-min.js:55:134]
